In [ ]:
cd

In [ ]:
import os
os.listdir('/tmp/../')

In [ ]:
import numpy as np
import pandas as pd
import os
import cv2
import matplotlib.pyplot as plt
from IPython.display import display
print('Files in this directory:',os.listdir('../kaggle/input'))

Files in this directory: ['test', 'train_labels.csv', 'train', 'sample_submission.csv']

In [ ]:
def f(x):
    display(x)

In [ ]:
images_list = os.listdir("../kaggle/input/train/")
print('Total number of training images:',len(images_list))

Total number of training images: 220025

In [ ]:
train_labels_df = pd.read_csv("../kaggle/input/train_labels.csv")
print("Total number of labels for training images: ",len(train_labels_df))

Total number of labels for training images:  220025

In [ ]:
train_labels_df.columns.tolist()

['id', 'label']

In [ ]:
print('First image id in training images:',images_list[0])
print("First image id in taining_labels csv:", train_labels_df.iloc[0,0])

#Visualize one image

In [ ]:
img = cv2.imread('../kaggle/input/train/'+ images_list[0]) #opencv color order BGR
rgb_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img)     #opencv BGR format   

In [ ]:
print('shape of img:',img.shape)

In [ ]:
plt.imshow(rgb_img) #matplotlib color order RGB

In [ ]:
print(type(train_labels_df.iloc[0,1]))
train_labels_df.iloc[0,1]

In [ ]:
print(type(train_labels_df.iloc[:,1]))
train_labels_df.iloc[:,1]

No. of positive and negative examples

In [ ]:
total_images = train_labels_df.iloc[:,0].tolist()
print('Total no of images: ', len(total_images))
non_tumor_images = train_labels_df[train_labels_df.iloc[:,1] == 0]['id'].tolist()
print('No. of non-tumor images:',len(non_tumor_images))
tumor_images = train_labels_df[train_labels_df.iloc[:,1] == 1]['id'].tolist()
print('No. of tumor images:',len(tumor_images))


In [ ]:
train_labels_df['label'].value_counts()

In [ ]:
# '.tif' is not there at the end of image ids in train_label.csv
tum_img = cv2.imread('../kaggle/input/train/' + tumor_images[550] + '.tif')
tum_img_grey = cv2.imread('../kaggle/input/train/' + tumor_images[550] + '.tif', cv2.IMREAD_GRAYSCALE)
tum_img = cv2.cvtColor(tum_img, cv2.COLOR_BGR2RGB)

non_tum_img = cv2.imread('../kaggle/input/train/' + non_tumor_images[250] + '.tif')
non_tum_img = cv2.cvtColor(non_tum_img, cv2.COLOR_BGR2RGB)

plt.imshow(tum_img)

In [ ]:
plt.imshow(tum_img_grey)

In [ ]:
tum_img_grey.shape

In [ ]:
plt.imshow(tum_img_grey, cmap = 'gray')

In [ ]:
non_tum_img.shape

In [ ]:
plt.imshow(non_tum_img)

In [ ]:
#AfterWork-  write functions given an 'img id' it shld return 0/1

Issue - training images ends with .tif, train_labels.csv 1st column id doesn't end with .tif

In [ ]:
print(images_list[0])
print(total_images[0])

Adding '.tif' at the end of each id in train_labels.csv

In [ ]:
train_labels_df.iloc[:,0] = [train_labels_df.iloc[:,0][i] + '.tif' for i in range(len(train_labels_df.iloc[:,0]))]

In [ ]:
train_labels_df.head()

In [ ]:
new_df = train_labels_df.copy()
new_df.head()

In [ ]:
train_images = new_df.iloc[:,0].tolist()

In [ ]:
column_names = [f'p{i}' for i in range(1, 48*48 +1)]
column_names[-1]
df1 = pd.DataFrame(columns = column_names)
df1.head()

In [ ]:
# # df1['index'] = [i for i in range(0,220025)]
# # df1['index'] = list(range(0,120025))
# df1['index']
# f(df1.head())
# f(df1.tail())

In [ ]:
p = cv2.imread('../kaggle/input/train/' + train_images[0], cv2.IMREAD_GRAYSCALE)
plt.imshow(p, cmap='gray')
p.shape

In [ ]:
plt.imshow(p[31:79,31:79], cmap = 'gray')
p[31:79,31:79].shape

In [ ]:
def crop(img):
    image = cv2.imread(img, cv2.IMREAD_GRAYSCALE)
    crop_img = image[31:79,31:79]
    return crop_img
    

In [ ]:
x = crop('../kaggle/input/train/'+train_images[0])
print('shape of x is:', x.shape)

So, we need to convert the shape fr_m (48,48) to (48,48,1)

In [ ]:
from numpy import newaxis
def crop_image(img):
    image = cv2.imread(img, cv2.IMREAD_GRAYSCALE)
    crop_img = image[31:79,31:79]
    crop_img = crop_img[:,:,newaxis]    
    return crop_img

In [ ]:
eg = crop_image('../kaggle/input/train/' + train_images[0])
print('shape of this image is:', eg.shape)
eg

In [ ]:
# f(len(train_data))
# f(type(train_data[0])) 
# train_data[0].shape

In [ ]:
from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
from keras.layers import Dropout

In [ ]:

classifier = Sequential()
classifier.add(Convolution2D(32,3,3, input_shape = (48,48,1), activation = 'relu'))
classifier.add(MaxPooling2D(pool_size=(2,2)))
classifier.add(Convolution2D(64,3,3, activation = 'relu'))
classifier.add(MaxPooling2D(pool_size=(2,2)))
classifier.add(Convolution2D(128,3,3, activation = 'relu'))
classifier.add(MaxPooling2D(pool_size=(2,2)))
classifier.add(Convolution2D(256,3,3, activation = 'relu'))
classifier.add(MaxPooling2D(pool_size=(2,2)))
classifier.add(Flatten())
classifier.add(Dense(output_dim = 256, activation = 'relu'))
classifier.add(Dense(output_dim = 128, activation = 'relu'))
classifier.add(Dense(output_dim = 64, activation = 'relu'))
classifier.add(Dense(output_dim = 1, activation = 'sigmoid'))

classifier.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])


In [ ]:
# def process(img):
#     img = cv2.imread(img, cv2.IMREAD_GRAYSCALE)
#     img.resize((img.shape[0]*img.shape[1]))
# #     return img

In [ ]:
# x = process('../kaggle//input/train/' + train_images[0])
# print('x from (96,96) shape to (96*96): ',x)

In [ ]:
# for i in range(220025):
#     row = process('../input/train/' + train_images[i])
#     df1.loc[i] = row

In [ ]:
# df1

In [ ]:
from sklearn.utils import shuffle
shuffled_data =shuffle(new_df)

In [ ]:
shuffled_data.head()

In [ ]:
len(shuffled_data)

In [ ]:
features = [crop_image('../kaggle/input/train/' + i) for i in  shuffled_data.iloc[:,0].tolist()]
print('Input features is a list containing ' + str(len(features)) + ' arrays')

In [ ]:
print('shape of each example is:',features[0].shape)

In [ ]:
labels = shuffled_data.iloc[:,1].tolist()
print("labels is a list of ouput labels containing 0's and 1's")

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(features, labels, test_size=0.3)

In [ ]:
print('Length of x_train', len(x_train))
print('Length of y_train', len(y_train))
print('Length of x_val', len(x_val))
print('Length of y_val', len(y_val))

In [ ]:
print('No. of tumor examples in y_train =', sum(y_train))
print('No. of non-tumor examples in y_train =', len(y_train) - sum(y_train))
print('No. of tumor examples in y_val =', sum(y_val))
print('No. of non-tumor examples in y_val =', len(y_val) - sum(y_val))

In [ ]:
print('type of x_train is:', type(x_train))
print('type of y_train is:', type(y_train))
print('type of x_val is:', type(x_val))
print('type of y_val is:', type(y_val))

But shape of data should be (examples, height, width, channels) which means its an array.

List doesn't have any shape. It only has length. 

So, we need to convert list into array.

Input features shape should be (examples, height, width, channels). For example (220025, 48, 48, 1)

In [ ]:
x_train = np.array(x_train)/255
x_val = np.array(x_val)/255

In [ ]:
x_train

In [ ]:
print('shape of x_train is:', x_train.shape)
print('shape of x_val is:', x_val.shape)

In [ ]:

from keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(shear_range = 0.2, zoom_range = 0.2,
                   horizontal_flip = True)
classifier.fit_generator(datagen.flow(x_train, y_train, batch_size=20),
                    steps_per_epoch=len(x_train) / 20, epochs = 70)


So, the training accuracy is_ : 81%

In [ ]:
70 epochs:
    Epoch 1/70
7701/7700 [==============================] - 82s 11ms/step - loss: 0.5062 - acc: 0.7616
Epoch 2/70
7701/7700 [==============================] - 77s 10ms/step - loss: 0.4801 - acc: 0.7792
Epoch 3/70
7701/7700 [==============================] - 76s 10ms/step - loss: 0.4716 - acc: 0.7844
Epoch 4/70
7701/7700 [==============================] - 75s 10ms/step - loss: 0.4653 - acc: 0.7875
Epoch 5/70
7701/7700 [==============================] - 75s 10ms/step - loss: 0.4597 - acc: 0.7914
Epoch 6/70
7701/7700 [==============================] - 75s 10ms/step - loss: 0.4532 - acc: 0.7930
Epoch 7/70
7701/7700 [==============================] - 74s 10ms/step - loss: 0.4507 - acc: 0.7965
Epoch 8/70
7701/7700 [==============================] - 74s 10ms/step - loss: 0.4478 - acc: 0.7970
Epoch 9/70
7701/7700 [==============================] - 74s 10ms/step - loss: 0.4443 - acc: 0.7986
Epoch 10/70
7701/7700 [==============================] - 73s 9ms/step - loss: 0.4417 - acc: 0.8000
Epoch 11/70
7701/7700 [==============================] - 73s 9ms/step - loss: 0.4396 - acc: 0.8020
Epoch 12/70
7701/7700 [==============================] - 73s 9ms/step - loss: 0.4368 - acc: 0.8027
Epoch 13/70
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4355 - acc: 0.8034
Epoch 14/70
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4331 - acc: 0.8049
Epoch 15/70
7701/7700 [==============================] - 73s 9ms/step - loss: 0.4326 - acc: 0.8062
Epoch 16/70
7701/7700 [==============================] - 73s 9ms/step - loss: 0.4308 - acc: 0.8074
Epoch 17/70
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4284 - acc: 0.8081
Epoch 18/70
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4275 - acc: 0.8079
Epoch 19/70
7701/7700 [==============================] - 73s 9ms/step - loss: 0.4263 - acc: 0.8102
Epoch 20/70
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4253 - acc: 0.8097
Epoch 21/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4237 - acc: 0.8102
Epoch 22/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4256 - acc: 0.8103
Epoch 23/70
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4219 - acc: 0.8122
Epoch 24/70
7701/7700 [==============================] - 73s 9ms/step - loss: 0.4224 - acc: 0.8116
Epoch 25/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4212 - acc: 0.8129
Epoch 26/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4191 - acc: 0.8143
Epoch 27/70
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4233 - acc: 0.8120
Epoch 28/70
7701/7700 [==============================] - 73s 9ms/step - loss: 0.4212 - acc: 0.8130
Epoch 29/70
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4216 - acc: 0.8128
Epoch 30/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4172 - acc: 0.8150
Epoch 31/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4169 - acc: 0.8152
Epoch 32/70
7701/7700 [==============================] - 73s 10ms/step - loss: 0.4172 - acc: 0.8148
Epoch 33/70
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4166 - acc: 0.8150
Epoch 34/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4148 - acc: 0.8159
Epoch 35/70
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4176 - acc: 0.8140
Epoch 36/70
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4148 - acc: 0.8172
Epoch 37/70
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4170 - acc: 0.8172
Epoch 38/70
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4126 - acc: 0.8180
Epoch 39/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4140 - acc: 0.8167
Epoch 40/70
7701/7700 [==============================] - 70s 9ms/step - loss: 0.4122 - acc: 0.8184
Epoch 41/70
7701/7700 [==============================] - 73s 9ms/step - loss: 0.4107 - acc: 0.8188
Epoch 42/70
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4123 - acc: 0.8179
Epoch 43/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4115 - acc: 0.8192
Epoch 44/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4089 - acc: 0.8207
Epoch 45/70
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4077 - acc: 0.8213
Epoch 46/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4159 - acc: 0.8165
Epoch 47/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4083 - acc: 0.8201
Epoch 48/70
7701/7700 [==============================] - 70s 9ms/step - loss: 0.4160 - acc: 0.8166
Epoch 49/70
7701/7700 [==============================] - 70s 9ms/step - loss: 0.4075 - acc: 0.8206
Epoch 50/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4052 - acc: 0.8214
Epoch 51/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4040 - acc: 0.8219
Epoch 52/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4112 - acc: 0.8196
Epoch 53/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4110 - acc: 0.8212
Epoch 54/70
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4087 - acc: 0.8188
Epoch 55/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4108 - acc: 0.8180
Epoch 56/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4030 - acc: 0.8228
Epoch 57/70
7701/7700 [==============================] - 69s 9ms/step - loss: 0.4039 - acc: 0.8220
Epoch 58/70
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4001 - acc: 0.8241
Epoch 59/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.3999 - acc: 0.8239
Epoch 60/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4069 - acc: 0.8219
Epoch 61/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4046 - acc: 0.8223
Epoch 62/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4039 - acc: 0.8219
Epoch 63/70
7701/7700 [==============================] - 73s 9ms/step - loss: 0.4040 - acc: 0.8230
Epoch 64/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4014 - acc: 0.8239
Epoch 65/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4095 - acc: 0.8220
Epoch 66/70
7701/7700 [==============================] - 70s 9ms/step - loss: 0.4034 - acc: 0.8231
Epoch 67/70
7701/7700 [==============================] - 72s 9ms/step - loss: 0.3996 - acc: 0.8233
Epoch 68/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4069 - acc: 0.8228
Epoch 69/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4079 - acc: 0.8212
Epoch 70/70
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4022 - acc: 0.8237

In [ ]:
# c = np.reshape(y, y.shape + (1,))  -> (48,48) to (48,48,1)

WARNING:tensorflow:From /opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/20
7701/7700 [==============================] - 79s 10ms/step - loss: 0.5148 - acc: 0.7533
Epoch 2/20
7701/7700 [==============================] - 74s 10ms/step - loss: 0.4845 - acc: 0.7763
Epoch 3/20
7701/7700 [==============================] - 74s 10ms/step - loss: 0.4765 - acc: 0.7813
Epoch 4/20
7701/7700 [==============================] - 75s 10ms/step - loss: 0.4717 - acc: 0.7839
Epoch 5/20
7701/7700 [==============================] - 76s 10ms/step - loss: 0.4640 - acc: 0.7881
Epoch 6/20
7701/7700 [==============================] - 74s 10ms/step - loss: 0.4588 - acc: 0.7918
Epoch 7/20
7701/7700 [==============================] - 74s 10ms/step - loss: 0.4549 - acc: 0.7935
Epoch 8/20
7701/7700 [==============================] - 75s 10ms/step - loss: 0.4515 - acc: 0.7958
Epoch 9/20
7701/7700 [==============================] - 77s 10ms/step - loss: 0.4471 - acc: 0.7990
Epoch 10/20
7701/7700 [==============================] - 74s 10ms/step - loss: 0.4446 - acc: 0.7992
Epoch 11/20
7701/7700 [==============================] - 74s 10ms/step - loss: 0.4417 - acc: 0.8008
Epoch 12/20
7701/7700 [==============================] - 74s 10ms/step - loss: 0.4387 - acc: 0.8026
Epoch 13/20
7701/7700 [==============================] - 76s 10ms/step - loss: 0.4366 - acc: 0.8041
Epoch 14/20
7701/7700 [==============================] - 73s 10ms/step - loss: 0.4346 - acc: 0.8042
Epoch 15/20
7701/7700 [==============================] - 74s 10ms/step - loss: 0.4335 - acc: 0.8065
Epoch 16/20
7701/7700 [==============================] - 75s 10ms/step - loss: 0.4318 - acc: 0.8068
Epoch 17/20
7701/7700 [==============================] - 76s 10ms/step - loss: 0.4299 - acc: 0.8077
Epoch 18/20
7701/7700 [==============================] - 74s 10ms/step - loss: 0.4273 - acc: 0.8098
Epoch 19/20
7701/7700 [==============================] - 74s 10ms/step - loss: 0.4265 - acc: 0.8092
Epoch 20/20
7701/7700 [==============================] - 74s 10ms/step - loss: 0.4254 - acc: 0.8100

In [ ]:
After rescaling:
    Epoch 1/20
7701/7700 [==============================] - 74s 10ms/step - loss: 0.5090 - acc: 0.7600
Epoch 2/20
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4840 - acc: 0.7770
Epoch 3/20
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4756 - acc: 0.7820
Epoch 4/20
7701/7700 [==============================] - 73s 9ms/step - loss: 0.4696 - acc: 0.7858
Epoch 5/20
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4642 - acc: 0.7887
Epoch 6/20
7701/7700 [==============================] - 77s 10ms/step - loss: 0.4602 - acc: 0.7915
Epoch 7/20
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4551 - acc: 0.7943
Epoch 8/20
7701/7700 [==============================] - 73s 9ms/step - loss: 0.4519 - acc: 0.7961
Epoch 9/20
7701/7700 [==============================] - 71s 9ms/step - loss: 0.4471 - acc: 0.7982
Epoch 10/20
7701/7700 [==============================] - 74s 10ms/step - loss: 0.4451 - acc: 0.7990
Epoch 11/20
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4424 - acc: 0.8010
Epoch 12/20
7701/7700 [==============================] - 73s 9ms/step - loss: 0.4379 - acc: 0.8037
Epoch 13/20
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4363 - acc: 0.8040
Epoch 14/20
7701/7700 [==============================] - 74s 10ms/step - loss: 0.4348 - acc: 0.8050
Epoch 15/20
7701/7700 [==============================] - 73s 9ms/step - loss: 0.4319 - acc: 0.8061
Epoch 16/20
7701/7700 [==============================] - 73s 9ms/step - loss: 0.4286 - acc: 0.8081
Epoch 17/20
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4279 - acc: 0.8082
Epoch 18/20
7701/7700 [==============================] - 73s 9ms/step - loss: 0.4246 - acc: 0.8098
Epoch 19/20
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4228 - acc: 0.8117
Epoch 20/20
7701/7700 [==============================] - 72s 9ms/step - loss: 0.4224 - acc: 0.8110
    
    

In [ ]:
weights = classifier.weights
weights

In [53]:
predictions = classifier.predict(x_val)
predictions

array([[0.10543382],
       [0.10795084],
       [0.07142514],
       ...,
       [0.11848363],
       [0.9671755 ],
       [0.0838984 ]], dtype=float32)

In [54]:
predictions.shape

(66008, 1)

In [55]:
predictions.resize(66008,)

In [56]:
predictions

array([0.10543382, 0.10795084, 0.07142514, ..., 0.11848363, 0.9671755 ,
       0.0838984 ], dtype=float32)

In [57]:
y_val_pred = list(predictions)

In [58]:
y_val_predicted = [1  if i > 0.5 else 0 for i in y_val_pred]
y_val_predicted2 = [1  if i > 0.1 else 0 for i in y_val_pred]

sum(y_val_predicted)

20552

In [59]:
sum(y_val_predicted2)

44506

In [60]:
np.unique(y_val_pred)

array([0.0000000e+00, 8.9406967e-08, 1.4901161e-07, ..., 9.9999976e-01,
       9.9999994e-01, 1.0000000e+00], dtype=float32)

In [61]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_val, y_val_predicted)

array([[35988,  3280],
       [ 9468, 17272]])

In [62]:
from sklearn.metrics import accuracy_score
accuracy_score(y_val, y_val_predicted)

0.8068718943158405

In [63]:
x_val2 = x_val
datagen.fit(x_val2)

In [64]:
predictions2 = classifier.predict(x_val2)
predictions2

array([[0.10543382],
       [0.10795084],
       [0.07142514],
       ...,
       [0.11848363],
       [0.9671755 ],
       [0.0838984 ]], dtype=float32)

In [65]:
sum(predictions2)

array([23232.752], dtype=float32)

In [66]:
np.unique(predictions2)

array([0.0000000e+00, 8.9406967e-08, 1.4901161e-07, ..., 9.9999976e-01,
       9.9999994e-01, 1.0000000e+00], dtype=float32)

In [67]:
predictions2.shape

(66008, 1)

In [68]:
predictions2.resize(66008,)
predictions2.shape

(66008,)

In [69]:
y_val_pred3 = list(predictions2)

In [70]:
y_val_predicted3 = [1  if i > 0.5 else 0 for i in y_val_pred3]

In [71]:
sum(y_val_predicted3)

20552

In [72]:
np.unique(y_val_predicted3)

array([0, 1])

In [73]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_val, y_val_predicted3)

array([[35988,  3280],
       [ 9468, 17272]])

In [74]:
from sklearn.metrics import accuracy_score
accuracy_score(y_val, y_val_predicted3)

0.8068718943158405

In [ ]:
classifier2 = Sequential()

classifier2.add(Convolution2D(32,3,3, input_shape = (48,48,1), activation = 'relu'))
classifier2.add(MaxPooling2D(pool_size=(2,2)))
classifier2.add(Dropout(0.2))

classifier2.add(Convolution2D(64,3,3, activation = 'relu'))
classifier2.add(MaxPooling2D(pool_size=(2,2)))
classifier2.add(Dropout(0.2))
classifier2.add(Convolution2D(128,3,3, activation = 'relu'))
classifier2.add(MaxPooling2D(pool_size=(2,2)))
classifier2.add(Dropout(0.2))

classifier2.add(Convolution2D(256,3,3, activation = 'relu'))
classifier2.add(MaxPooling2D(pool_size=(2,2)))
classifier2.add(Dropout(0.2))

classifier2.add(Flatten())
classifier2.add(Dense(output_dim = 256, activation = 'relu'))
classifier2.add(Dropout(0.2))
classifier2.add(Dense(output_dim = 128, activation = 'relu'))
classifier2.add(Dropout(0.2))
classifier2.add(Dense(output_dim = 64, activation = 'relu'))
classifier2.add(Dropout(0.2))
classifier2.add(Dense(output_dim = 1, activation = "sigmoid"))

classifier2.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

classifier2.summary()

In [ ]:
from keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(rescale = 1./255, shear_range = 0.2, zoom_range = 0.2,
                   horizontal_flip = True)
datagen.fit(x_train)
classifier2.fit_generator(datagen.flow(x_train, y_train, batch_size=20),
                    steps_per_epoch=len(x_train) / 20, epochs = 20)

If we use dropout:
Epoch 1/20
7701/7700 [==============================] - 83s 11ms/step - loss: 0.6758 - acc: 0.5944
Epoch 2/20
7701/7700 [==============================] - 79s 10ms/step - loss: 0.6754 - acc: 0.5945
Epoch 3/20
7701/7700 [==============================] - 79s 10ms/step - loss: 0.6753 - acc: 0.5945
Epoch 4/20
7701/7700 [==============================] - 79s 10ms/step - loss: 0.6753 - acc: 0.5945
Epoch 5/20
7701/7700 [==============================] - 80s 10ms/step - loss: 0.6753 - acc: 0.5945
Epoch 6/20
7701/7700 [==============================] - 78s 10ms/step - loss: 0.6752 - acc: 0.5945
Epoch 7/20
7701/7700 [==============================] - 79s 10ms/step - loss: 0.6752 - acc: 0.5945
Epoch 8/20
7701/7700 [==============================] - 78s 10ms/step - loss: 0.6752 - acc: 0.5945
Epoch 9/20
7701/7700 [==============================] - 80s 10ms/step - loss: 0.6752 - acc: 0.5945
Epoch 10/20
7701/7700 [==============================] - 79s 10ms/step - loss: 0.6752 - acc: 0.5945
Epoch 11/20
7701/7700 [==============================] - 78s 10ms/step - loss: 0.6752 - acc: 0.5945
Epoch 12/20
7701/7700 [==============================] - 79s 10ms/step - loss: 0.6752 - acc: 0.5945
Epoch 13/20
7701/7700 [==============================] - 79s 10ms/step - loss: 0.6752 - acc: 0.5945
Epoch 14/20
7701/7700 [==============================] - 79s 10ms/step - loss: 0.6752 - acc: 0.5945
Epoch 15/20
7701/7700 [==============================] - 78s 10ms/step - loss: 0.6752 - acc: 0.5945
Epoch 16/20
7701/7700 [==============================] - 78s 10ms/step - loss: 0.6752 - acc: 0.5945
Epoch 17/20
7701/7700 [==============================] - 80s 10ms/step - loss: 0.6752 - acc: 0.5945
Epoch 18/20
7701/7700 [==============================] - 79s 10ms/step - loss: 0.6752 - acc: 0.5945
Epoch 19/20
7701/7700 [==============================] - 78s 10ms/step - loss: 0.6752 - acc: 0.5945
Epoch 20/20
7701/7700 [==============================] - 79s 10ms/step - loss: 0.6752 - acc: 0.5945

    

In [ ]:
weights2 = classifier2.weights
weights2

In [75]:
predictions4 = classifier.predict(x_val)
predictions4

array([[0.10543382],
       [0.10795084],
       [0.07142514],
       ...,
       [0.11848363],
       [0.9671755 ],
       [0.0838984 ]], dtype=float32)

In [76]:
predictions4.resize(66008,)
predictions4

array([0.10543382, 0.10795084, 0.07142514, ..., 0.11848363, 0.9671755 ,
       0.0838984 ], dtype=float32)

In [77]:
y_val_pred4 = list(predictions4)
y_val_predicted4 = [1  if i > 0.5 else 0 for i in y_val_pred4]
sum(y_val_predicted4)


20552

In [78]:
np.unique(y_val_pred4)

array([0.0000000e+00, 8.9406967e-08, 1.4901161e-07, ..., 9.9999976e-01,
       9.9999994e-01, 1.0000000e+00], dtype=float32)

In [79]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_val, y_val_predicted4)

array([[35988,  3280],
       [ 9468, 17272]])

In [80]:
from sklearn.metrics import accuracy_score
accuracy_score(y_val, y_val_predicted4)

0.8068718943158405

In [82]:
test_images = os.listdir("../kaggle/input/test/")
print('Total number of training images:',len(test_images))


Total number of training images: 57458


In [84]:
test_features = [crop_image('../kaggle/input/test/' + i) for i in  test_images]
test_features = np.array(test_features)
test_features = test_features/255
test_features[0]
test_features.shape

(57458, 48, 48, 1)

In [93]:
test_preds = classifier.predict(test_features)
test_preds.resize(57458,)
list(test_preds)
test_values = [1  if i > 0.5 else 0 for i in test_preds]

[0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,


In [94]:
sum(test_values)

16775

In [113]:
df = {}
df['id'] = [i.split('.')[0] for i in test_images]
df['label'] = test_values

In [114]:
test_images[0]

'7bea07522c81d67df5a851edbfbc85256d784972.tif'

In [115]:
import pandas as pd

In [116]:
DataFrame = pd.DataFrame.from_dict(df)
DataFrame

id  label
0      7bea07522c81d67df5a851edbfbc85256d784972      0
1      f8a3d75f17a491962d457ecdfb206df9b46f8523      0
2      7439cca1423496ba24df0f3933a7cf59ae6f98fd      0
3      7c115503f55a03bc205d24e09c8b4081508156f3      0
4      25d9e2b55c4e7d515ec5712bd0b8839e67946e0e      1
5      95f7dc266784cb1f4ba975ed508f70abe6e9b32d      0
6      a4386a0ab03f3d9e5b0983aebb0df93ee959d50e      1
7      1568575fbf58300ed259482bddac3baa9e9e9ddc      0
8      dad8381621b914ac1335693f2f20198317abfec2      0
9      4baa1154d7acf03e4a70232e72ad2bd97def0db7      0
10     00af1151d5a87d93f50001e20236ec50ec6112e3      0
11     5524664914331c65fbcf9fc0593280c51f1b6002      1
12     336328b2faae0f7d579d8874b4c22d3b91b6c055      0
13     32e27a2f9a61535c9f534ea8908e7f1f501e675a      1
14     88d08024fbc372967fbf391e1bcf5ce4e31353d8      1
15     5f0db9805fe0da9cdcf5336dcf3c26741eeb3b53      0
16     d83d2f0717d927efa6fa878558c652e2fe7b9fe9      1
17     359e7b39cc671a51439bc1e261c502a586113f46      0
18     8c6850998c138d1006de40982be4f4cb2d37a99b      1
19     6e53634fd4baee13610c5c4fe5ff904e81edaca1      1
20     4f7a67e3ee3109a3c45e8df805517a9210dd954c      0
21     ace25a96ca7fa0a7716fa4b31d1714d5dcf18bf2      0
22     8db5c90e69be180af45db250a28181950d914d5a      0
23     fbce3c28e8b7be2418d6b2a54f6a120ebb48a114      0
24     6825c56c61b1463c9e3cd52eb70e52deeb74b1d2      0
25     fa6db975d98c3078be042352578beb1802d03402      0
26     8d7ad77eaaf6b5fd8423a145d4bc3b2bce34a617      1
27     6f8b61fd1a4de8b0687d1cc4bef77ae6cef564a1      1
28     c79d6cc622fd8c3dbd8ae6f3300b134927cd621f      0
29     61b7a2fc51832b782c20e73b92a9dd0f479c36f9      0
...                                         ...    ...
57428  e0dcec62412556a22510d223506ab1dfa647880e      0
57429  9a6ef313aef9583db3970a73074639b035ecc2c4      0
57430  caf4480bbfb7c3ad51340dfc961e42ced1c840f9      1
57431  6c68590dc95ee97eb5eb4c0f992a06f85c96061e      0
57432  c42c85149c39e9bd8951aab8c37b83645a6b9bbb      0
57433  36bf2a58a3a5038bc48317e9422711be9f19884a      0
57434  e109e95cf34f184f399777b6e08e7febc46ecd8c      1
57435  12c4110cb89a307bda246ea7edc1c5882cf9d3f2      1
57436  f7f07d81c3db20895edf01c7e86cc3ce88d7088b      0
57437  62aacb3d09e5cb8d5f602885dc012756aa5fa8d5      1
57438  6e6226458e66b429c6009af236b02ffdaa6c1fb9      0
57439  8e44406f6ea0f0e887f522e4c7929188c3746a9c      0
57440  8ae5b9f7d44baabb5ab41867524c72096e52526f      0
57441  d3efb28c3049033c1ccfa7b0037f4439f1c0699e      1
57442  dbf3619fac4d04acc6a6520941c0c8ecb9a26bff      0
57443  bbcbdb169613a94714eabe493773945cdc9b9ad5      0
57444  350a1b8c3a7ce3714645bd62cfab1ee819e5e6bb      1
57445  81f3232fd4d36f280f3d618d64c6f923e24eb801      0
57446  d035b942246b8b551fcb7a69cf6c42b6ffa7307a      1
57447  5a240f8398c5d5a77630937a91ae9e7a6343ec0a      0
57448  ff9539b3decb96115b861d66ddb0cc67399ff649      0
57449  caccbc8dfce30c0dc784f0547087505507242197      0
57450  9ae954313b9082ab73db639c4464e7ad7aa9d415      0
57451  bda410323103afd3714ce06481f80bbd82b8695b      1
57452  5e4383bc606c3d1a44e745f4da107d2d14903e7b      1
57453  7b8c3b004dd25081fcb0913598e34e547d76da6f      0
57454  5dd7b448ef37c7dd2a8fdcf7cf751f1cc8679171      0
57455  f7ddbdddb6b7fb038d0186e0568430957eb3f8a1      0
57456  6a5a79d26ea0e3eaea34b892e9e9f9f5941a6198      0
57457  14ea8430f013264bfdfc93d7a3303cc168266f73      0

[57458 rows x 2 columns]

In [112]:
submission_file = pd.read_csv('../kaggle/input/sample_submission.csv')

id  label
0      0b2ea2a822ad23fdb1b5dd26653da899fbd2c0d5      0
1      95596b92e5066c5c52466c90b69ff089b39f2737      0
2      248e6738860e2ebcf6258cdc1f32f299e0c76914      0
3      2c35657e312966e9294eac6841726ff3a748febf      0
4      145782eb7caa1c516acbe2eda34d9a3f31c41fd6      0
5      725dabe6ecccc68b958a2c7dd75bcbf362c7cb03      0
6      aa0307865281d4484ddf8c637c348292968b93a7      0
7      f4e5dc9c949920f1b3362982e15e99bf6f3ef83b      0
8      95e08c9cedc28a9b4a86f4fc1e06c1972134be08      0
9      ee1f5345a8d4e28403b7e61b97b5f76c201ce9cb      0
10     14b1e9a72e27a35f13056db611feb3c8825916f4      0
11     4f7710b24b9b776f6bfc89fad5469592d18e5431      0
12     2b0668109c7c446c94d29e1b554016b486e84bde      0
13     8dbd712b5b5e86c18c97da3fb7845cfe23cdf1c5      0
14     0084317dbb3398aed9f7c915c2cdef5a07ada5be      0
15     5685c695bb0926d8ce434bb787a58affdc9277df      0
16     715ea4b61896620422f4c9c954db514077633745      0
17     a218c12c700277dd50b2da4e0e3a0089d5094186      0
18     c0a44513db67635cc99370f24d962e272dbf7a11      0
19     dd52e9ad03e746aff71b1d81c1cf168ec6dcdf57      0
20     a67f22a204960680de09f88c9a588014e78e314c      0
21     5a895b4562c4d67d194b76094690a8cba046f9f3      0
22     09f704e216dab50f7d759746bb1f132cc7b59939      0
23     e1d48393c5fa0bca3d3469f8a42e1991f2939a3d      0
24     42301acb5c16684fbde86e0210f19f6adf232316      0
25     4c3b7d71422fe2c35153a821c84538516ee89573      0
26     edf908d325da428766464beb035c744e589e2ba0      0
27     c68144b44b49d96d4b2e1870f854781a84ec3e20      0
28     81d0aa3c20f021c2fc12a79c359ea29fa499425f      0
29     564804ca8f0e05b7790108a24e7f2a36f1732375      0
...                                         ...    ...
57428  c3936a5ab82c8429d337c2af505d12e8fed53800      0
57429  3a51838cb2d914b1eae479ed07887a25ad898130      0
57430  5cd2c886445fa12b1a5fd7476f59f6b9ff641048      0
57431  73b6d3a082011e64bff624fe718bb66cc7757572      0
57432  5bb1f5a647fed58bfa69a820f16c959e4f8e418b      0
57433  cbfe076d09dbbfe899d2276d38d1e6b2669e06b9      0
57434  3f713d1d1b0e8cd18daf3bc014b21f09f243ac4d      0
57435  5e6e3443a9145a43e10e4fcc35df3fd8bc3c4411      0
57436  aaff0630a066416f374cd2e65a169d8378840376      0
57437  a36a9295354c700739b369dd7de4df54e801c185      0
57438  86cbac8eef45d436a8b1c7469ada0894f0b684cc      0
57439  64c1b67a3d4409c3de1da54b88771da63620dd53      0
57440  da50fba013af3e308867f47183e7d037f574dc10      0
57441  b0f5c94b69b5c76a5f0a9364c5d102826d29e0b3      0
57442  8464c48f09addf99e79aee5422a66cfff48c2929      0
57443  f18483fb465cd92c73b5f5e775f23b58cc5b2d36      0
57444  d92e5dc32ff59711a94e0f4edfcd6a8b2eff583f      0
57445  7e43b15f9b04dfa36a80ffc8787a2115fe3633df      0
57446  1817497e85ef6d779852d4bae488b45fbccb4305      0
57447  7c553e582d5a67f2bc90273d8f62940f6d46aba0      0
57448  5481ea07d17fed3a807294a1c2ddbba2a64eb9e3      0
57449  d5b3051b33d56ae6b46069225739ba2005d3ae61      0
57450  69097bf5ae9632515d2e70c7cd3880ea7980820c      0
57451  a3c0f54a1e82f1bb3f9527eb619cec2bb229fa5d      0
57452  f93cadad45c3d7763af25d3412bd0019a95fa0f1      0
57453  061847314ded6f81e1cd670748bfa2003442c9c7      0
57454  6f3977130212641fd5808210015a609c658dcbff      0
57455  46935f247278539eca74b54d07d666efb528a753      0
57456  a09bcae08a82120183352e0e869181b2911d3dc1      0
57457  d29233dc0b90c2e1a8fcedbc3e1234c3d4dbd55b      0

[57458 rows x 2 columns]

In [117]:
submission = DataFrame
submission.to_csv('predictions.csv', columns=['label']) 

In [118]:
submission.head()

id  label
0  7bea07522c81d67df5a851edbfbc85256d784972      0
1  f8a3d75f17a491962d457ecdfb206df9b46f8523      0
2  7439cca1423496ba24df0f3933a7cf59ae6f98fd      0
3  7c115503f55a03bc205d24e09c8b4081508156f3      0
4  25d9e2b55c4e7d515ec5712bd0b8839e67946e0e      1